name: monami
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cloud_firestore: null
  collection: null
  cupertino_icons: ^1.0.2
  device_preview: null
  equatable: ^2.0.5
  firebase_auth: null
  firebase_core: null
  firebase_storage: null
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_svg: ^2.0.9
  font_awesome_flutter: null
  gap: ^3.0.1
  get_it: ^7.6.0
  google_fonts: ^5.1.0
  google_sign_in: ^6.0.2
  hooks_riverpod: ^2.3.0
  image: null
  image_picker: ^1.0.1
  intl: null
  lottie: ^2.2.0
  share_plus: ^7.0.2
  url_launcher: ^6.1.10
  uuid: ^3.0.7
  video_player: ^2.6.0
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/grocery_images/
    - assets/icons/
    - assets/animations/loading.json
    - assets/animations/error.json
    - assets/animations/small_error.json
    - assets/animations/empty.json
    - assets/animations/data_not_found.json
    - shorebird.yaml
