// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyAzmN2cwQdzSRqo6GYK_WtaqjcKcQKYI',
    appId: '1:287710446077:web:16138769e4763917169994',
    messagingSenderId: '287710446077',
    projectId: 'awesome-monami',
    authDomain: 'awesome-monami.firebaseapp.com',
    storageBucket: 'awesome-monami.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClEL2RL_v_Y-ZGCxZ97rBBN5uGzTeAZGI',
    appId: '1:287710446077:android:96bec315decff5eb169994',
    messagingSenderId: '287710446077',
    projectId: 'awesome-monami',
    storageBucket: 'awesome-monami.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc7YHpUPBiqOzFDnvbifm4i7My8AnKuXE',
    appId: '1:287710446077:ios:aff347d5b0d97ea8169994',
    messagingSenderId: '287710446077',
    projectId: 'awesome-monami',
    storageBucket: 'awesome-monami.appspot.com',
    iosClientId: '287710446077-2q1nqhtuq746ak40gdsbbvk8r5obhjcv.apps.googleusercontent.com',
    iosBundleId: 'com.example.monami',
  );
}
